[package]
name = "may"
version = "0.2.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/Xudong-Huang/may.git"
homepage = "https://github.com/Xudong-Huang/may.git"
documentation = "https://docs.rs/may"
description = "Rust Stackful Coroutine Library"
readme = "README.md"
keywords = ["coroutine", "async", "multi-thread"]
categories = ["concurrency"]
build = "build.rs"
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
    "benches/**/*",
    "docs/**/*",
]

[badges]
travis-ci = { repository = "Xudong-Huang/may" }
appveyor = { repository = "Xudong-Huang/may", service = "github" }

[dependencies]
log = "0.4"
time = "0.1"
socket2 = { version = "0.3", features = ["unix"] }
smallvec = "0.6"
generator = "0.6"
crossbeam = "0.3"
crossbeam-deque = "0.1"
may_queue = { version = "0.1", path = "may_queue" }
num_cpus = "1.0"

[target.'cfg(unix)'.dependencies]
nix = "0.9"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
miow = "0.3"
winapi = "0.3"

[dev-dependencies]
bytes = "0.4"
serde = "1.0"
docopt = "0.8"
tempdir = "0.3"
httparse = "1.1"
native-tls = "0.1"
tungstenite = "0.5"
serde_derive = "1.0"


[profile.release]
opt-level=3
lto = true

[build-dependencies]
rustc_version = "0.2"

[workspace]
